### PR TITLE
Various WYSIWYG bug fixes

### PR DESCRIPTION
**Pull request by goblincore**
Notable Fixes and changes include:
- Fix for mentions bug where inserting a new mention in front of existing text would delete the text after inserting the new mention
- Fix issue where typing an underscore would italicize everything (this happens alot to me!!)
- Fix issue where empty spacer would cause input element size to increase (happens when using mentions and there are no results)
- Convert Richmarkdown Editor and Minimal Editor to FC
- Add maxLength prop and plugin to allow for limiting content length when using WYSIWYG

### CODE REVIEW

**Comment by goblincore** [comment]
@smurflo2 Sweet, saw your mentions changes and comments - super helpful explanation, working good for me now when using @'First Lastname' 
@TaylorBeeston Nice with the refactor! I'm getting a few TSC terrors when building: 

```

src/MinimalEditor.tsx:509:33 - error TS2322: Type 'Object[] | undefined' is not assignable to type 'any[]'.
  Type 'undefined' is not assignable to type 'any[]'.

509                                 participants={participants}
                                    ~~~~~~~~~~~~

  src/components/MentionsMenu.tsx:15:5
    15     participants: Array<any>;
           ~~~~~~~~~~~~
    The expected type comes from property 'participants' which is declared here on type 'IntrinsicAttributes & MentionsMenuProps & { children?: ReactNode; }'

src/RichMarkdownEditor.tsx:553:33 - error TS2322: Type 'Object[] | undefined' is not assignable to type 'any[]'.
  Type 'undefined' is not assignable to type 'any[]'.

553                                 participants={participants}
                                    ~~~~~~~~~~~~

  src/components/MentionsMenu.tsx:15:5
    15     participants: Array<any>;
           ~~~~~~~~~~~~
    The expected type comes from property 'participants' which is declared here on type 'IntrinsicAttributes & MentionsMenuProps & { children?: ReactNode; }'
```

**Comment by TaylorBeeston** [comment]
@goblincore whoops! Last night I refactored out most of the editor logic into a `useEditor` hook, and apparently forgot to push it up! 🙃 TS errors are fixed with that commit!

**Comment by goblincore** [comment]
@TaylorBeeston Sweet, yeah I'll push up a few more fixes from master and also update the prosemirror packages to latest versions, and move them from peer deps so we can remove those prosemirror packages from the main frontend, then do a lil more testing and we can publish

**Comment by TaylorBeeston** [comment]
@goblincore sweet! I'm doing another quick refactor because I realized more logic should go in that `useEditor` hook!

**Pull request merged**
